name: Application

on:
  push:
    branches: [main]
    paths:
      - "app/**"
      - "deploy/app/**"
      - ".github/workflows/app.yaml"

  pull_request:
    branches: [main]
    paths:
      - "app/**"
      - "deploy/app/**"
      - ".github/workflows/app.yaml"

  workflow_dispatch:

permissions:
  id-token: write
  contents: read
  pull-requests: write

jobs:
  build_push:
    strategy:
      fail-fast: true
      matrix:
        stack: [app]
        environment:
          {%- for env in cookiecutter.environments %}
          - @{{ env }}
          {%- endfor %}
    uses: tx-pts-dai/github-workflows/.github/workflows/docker-build-push-ecr.yaml@v1
    with:
      environment: ${{ matrix.stack }}-${{ matrix.environment }}
      docker_context: app

  plan:
    if: github.event_name == 'pull_request'
    needs: [build_push]
    strategy:
      fail-fast: false
      matrix:
        stack: [app]
        environment:
          {%- for env in cookiecutter.environments %}
          - @{{ env }}
          {%- endfor %}
    uses: tx-pts-dai/github-workflows/.github/workflows/tf-plan.yaml@v1
    with:
      environment: ${{ matrix.stack }}-${{ matrix.environment }}
      tf_vars: |
        image_tag="${{ github.sha }}"

  apply:
    if: github.ref_name == github.event.repository.default_branch && (github.event_name == 'push' || github.event_name == 'workflow_dispatch')
    needs: [build_push]
    strategy:
      fail-fast: true
      max-parallel: 1
      matrix:
        stack: [app]
        environment:
          {%- for env in cookiecutter.environments %}
          - @{{ env }}
          {%- endfor %}
    uses: tx-pts-dai/github-workflows/.github/workflows/tf-apply.yaml@v1
    with:
      environment: ${{ matrix.stack }}-${{ matrix.environment }}
      tf_vars: |
        image_tag="${{ github.sha }}"
