name: Cleanup Feature Branch

on:
  pull_request:
    types:
      - closed

permissions:
  id-token: write
  contents: read
  pull-requests: write

jobs:
  destroy_feature:
    name: Destroy Feature Branch
    strategy:
      max-parallel: 1
      matrix:
        stack: [app]
        environment: [preview]
    uses: tx-pts-dai/github-workflows/.github/workflows/tf-cleanup.yaml@v2
    with:
      tf_workspace: ${{ github.head_ref }}
      tf_vars: |
        image_tag="not_needed_for_destroy"
        branch="${{ github.head_ref }}"
      environment: ${{ matrix.stack }}-${{ matrix.environment }}
