name: Infrastructure

on:
  push:
    branches: [main, master]
    paths:
      - "deploy/infra/**"
      - ".github/workflows/infra.yaml"

  pull_request:
    branches: [main, master]
    paths:
      - "deploy/infra/**"
      - ".github/workflows/infra.yaml"

  workflow_dispatch:

permissions:
  id-token: write
  contents: read
  pull-requests: write

jobs:
  plan:
    if: github.event_name == 'pull_request'
    strategy:
      fail-fast: false
      matrix:
        stack: [infra]
        environment:
          {%- for env in cookiecutter.environments %}
          - @{{ env }}
          {%- endfor %}
          {%- if not cookiecutter.github_environments %}
        include:
        {%- for env, values in cookiecutter.environments.items() %}
          - environment: @{{ env }}
            aws_account_id: @{{ values.aws_account_id }}
            aws_region: @{{ values.tf_state_region }}
            aws_role_name: @{{ values.aws_role_name }}
        {%- endfor %}
        {%- endif %}
    uses: tx-pts-dai/github-workflows/.github/workflows/tf-plan.yaml@v1
    with:
      {%- if cookiecutter.github_environments %}
      environment: ${{ matrix.stack }}-${{ matrix.environment }}
      {%- else %}
      aws_region: ${{ matrix.aws_region }}
      aws_oidc_role_arn: arn:aws:iam::${{ matrix.aws_account_id }}:role/${{ matrix.aws_role_name }}
      tf_dir: "deploy/infra"
      tf_backend_config_files: "deploy/infra/environments/${{ matrix.environment }}.s3.tfbackend"
      tf_var_files: "deploy/infra/${{ matrix.environment }}.tfvars"
      {%- endif %}


  apply:
    if: github.ref_name == github.event.repository.default_branch && (github.event_name == 'push' || github.event_name == 'workflow_dispatch')
    strategy:
      fail-fast: true
      max-parallel: 1
      matrix:
        stack: [infra]
        environment:
          {%- for env in cookiecutter.environments %}
          - @{{ env }}
          {%- endfor %}
          {%- if not cookiecutter.github_environments %}
        include:
        {%- for env, values in cookiecutter.environments.items() %}
          - environment: @{{ env }}
            aws_account_id: @{{ values.aws_account_id }}
            aws_region: @{{ values.tf_state_region }}
            aws_role_name: @{{ values.aws_role_name }}
        {%- endfor %}
        {%- endif %}
    uses: tx-pts-dai/github-workflows/.github/workflows/tf-apply.yaml@v1
    with:
      {%- if cookiecutter.github_environments %}
      environment: ${{ matrix.stack }}-${{ matrix.environment }}
      {%- else %}
      aws_region: ${{ matrix.aws_region }}
      aws_oidc_role_arn: arn:aws:iam::${{ matrix.aws_account_id }}:role/${{ matrix.aws_role_name }}
      tf_dir: "deploy/infra"
      tf_backend_config_files: "deploy/infra/environments/${{ matrix.environment }}.s3.tfbackend"
      tf_var_files: "deploy/infra/${{ matrix.environment }}.tfvars"
      {%- endif %}
